### ISSUE TITLE
Unable to install on Go 1.19

### ISSUE THREAD

**Issue by swishkin** [ntsd/cross-clipboard#1]
When attempting to install on an Artix Linux system with Go 1.19 installed, install for quic-go fails with the below error:

```
# github.com/lucas-clemente/quic-go/internal/qtls
go/pkg/mod/github.com/lucas-clemente/quic-go@v0.27.0/internal/qtls/go119.go:6:13: cannot use "The version of quic-go you're using can't be built on Go 1.19 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.19 yet. F...) as int value in variable declaration
```

I believe appending a newer version (0.28.0 seems to be where they began supporting Go 1.19) in [this file](https://github.com/ntsd/cross-clipboard/blob/3ca92a63d103bb8582d5314eea35c045d20e7758/go.sum#L541) may resolve the issue, but I'm no coder.

Thanks for the code, I hope to use it soon.

**Comment by ntsd** [comment]
Hi @swishkin, 

I just released a new version that supports Go 1.9 [v0.1.2](https://github.com/ntsd/cross-clipboard/releases/tag/v0.1.2).

Thank you for your interest in this project. It's still in beta.

**Comment by ntsd** [comment]
Hi @swishkin,

Would you give some feedback if it works? I am now making it for mobile.
The clipboard and network already work but still no UI for mobile yet.

**Comment by swishkin** [comment]
Ok, I tried installing again via `go install github.com/ntsd/cross-clipboard@latest`, and it gave me no errors.

However, the app doesn't seem to have installed properly, as neither `cross-clipboard` nor `cross-clipboard -t` are recognized.

**Comment by ntsd** [comment]
> Ok, I tried installing again via `go install github.com/ntsd/cross-clipboard@latest`, and it gave me no errors.
> 
> However, the app doesn't seem to have installed properly, as neither `cross-clipboard` nor `cross-clipboard -t` are recognized.

You can try to path your go bin by `export PATH=$PATH:$(go env GOPATH)/bin` or `echo "export PATH=$PATH:$(go env GOPATH)/bin" >> ~/.profile` 

for the explain https://medium.com/learn-go/go-path-explained-cab31a0d90b9

**Comment by swishkin** [comment]
I apologize for my late reply here; I can't remember if I tried to build on Linux or Windows previously, but the below attempts are on Linux. I'm not sure if I'm (still) doing something wrong, but I cloned the repo, ran `go build .`, and received the same error:

```
# github.com/lucas-clemente/quic-go/internal/qtls
../.local/share/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.31.1/internal/qtls/go120.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
```

I also tried running `go install github.com/ntsd/cross-clipboard@latest`, and it gives the same error.

Do I need to downgrade Go to build/install cross-clipboard? 

Edit: it looks like quic-go has moved its repo to a new [organization repo](https://github.com/quic-go/quic-go) for quic-go, so references in code to `lucas-clemente` may need to be changed to `quic-go`.
